### PR TITLE
fix EnclosedMessage header lines (fixes #571)

### LINKED ISSUE #571: Enclosed Message "To" header - internal Redwood::Person object displayed
For an Enclosed Message's "To" header, the "To" line of the expanded enclosed message shows a `to_s` of the internal `Redwood::Person` Ruby object(s), rather than the expected normal "To" header format.

See [enclosed-message-demo.txt](https://github.com/sup-heliotrope/sup/files/4909577/enclosed-message-demo.txt) - currently displays similarly to:
```
From: enclosed-sender <enclosed-sender@example.com>
To: [#<Redwood::Person:0x000055aa981f11f0 @name="enclosed-recipient",
@email="enclosed-recipient@example.com">]
Date:
Subject: Enclosed subject line

Demo enclosed message
```

### PR DESCRIPTION
**Pull request by IPv2**
In class `EnclosedMessage` (within `lib/sup/message_chunks.rb`):

* Ternary operator logic was backwards, e.g., setting `@from` to `"unknown sender"` if and only if `from` was truthy(!)

* `@lines` was constructed using local variables instead of instance variables, which (happily?) masked the effects of the above backwards ternary logic. But this also created issue #571: `Redwood::Person` object representations were shown directly to the user, rather than the human-friendly parsed strings intended to be shown by `Redwood::Person#full_address`.

* `@lines` was constructed as a single string (with literal line breaks), instead of following the normal convention of an array of lines. This hindered testability.

In this commit, we:

1. Fix the above three issues in `EnclosedMessage`.

2. Uncomment and expand upon the "TODO" tests for `EnclosedMessage` headers. These placeholders were added in PR #569, credit @danc86.

3. Modify `test/fixtures/non-ascii-header-in-nested-message.eml` to follow best practices for a testing email address, i.e., use reserved `.invalid` domain instead of `b.c` - to ensure that the testing email address remains invalid forever.

### CODE REVIEW

File: test/test_message.rb [hunk 1]
```diff
@@ -261,10 +261,10 @@ def test_nonascii_header_in_nested_message
     assert(chunks[0].is_a? Redwood::Chunk::Text)
 
     assert(chunks[1].is_a? Redwood::Chunk::EnclosedMessage)
-    ## TODO need to fix EnclosedMessage#lines
-    #assert_equal(4, chunks[1].lines.length)
-    #assert_equal("From: SPAM \ufffd <spammer@example.com>", chunks[1].lines[0])
-    #assert_equal("spam \ufffd spam", chunks[1].lines[3])
+    assert_equal(4, chunks[1].lines.length)
+    assert_equal("From: SPAM \ufffd <spammer@example.com>", chunks[1].lines[0])
+    assert_equal("To: enclosed <enclosed@example.invalid>", chunks[1].lines[1])
```
Comment (danc86) [inline test/test_message.rb:266]: We could also add a dedicated test case for enclosed messages and cover this more completely (we could assert the lines that make up the body of the enclosed message too).

Comment (IPv2) [reply test/test_message.rb:266]: Good idea - I'll add in a new PR

Comment (IPv2) [reply test/test_message.rb:266]: PR #575
